// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	browser "github.com/agent-infra/sandbox-sdk-go/browser"
	code "github.com/agent-infra/sandbox-sdk-go/code"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	file "github.com/agent-infra/sandbox-sdk-go/file"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	jupyter "github.com/agent-infra/sandbox-sdk-go/jupyter"
	mcp "github.com/agent-infra/sandbox-sdk-go/mcp"
	nodejs "github.com/agent-infra/sandbox-sdk-go/nodejs"
	option "github.com/agent-infra/sandbox-sdk-go/option"
	sandbox "github.com/agent-infra/sandbox-sdk-go/sandbox"
	shell "github.com/agent-infra/sandbox-sdk-go/shell"
	util "github.com/agent-infra/sandbox-sdk-go/util"
)

type Client struct {
	WithRawResponse *RawClient
	Sandbox         *sandbox.Client
	Shell           *shell.Client
	File            *file.Client
	Jupyter         *jupyter.Client
	Nodejs          *nodejs.Client
	Mcp             *mcp.Client
	Browser         *browser.Client
	Code            *code.Client
	Util            *util.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Sandbox:         sandbox.NewClient(options),
		Shell:           shell.NewClient(options),
		File:            file.NewClient(options),
		Jupyter:         jupyter.NewClient(options),
		Nodejs:          nodejs.NewClient(options),
		Mcp:             mcp.NewClient(options),
		Browser:         browser.NewClient(options),
		Code:            code.NewClient(options),
		Util:            util.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Serve the terminal HTML page
func (c *Client) ServeTerminalTerminalGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.ServeTerminalTerminalGet(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
