// Code generated by Fern. DO NOT EDIT.

package sandbox

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get sandbox environment information
func (c *Client) GetContext(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.SandboxResponse, error) {
	response, err := c.WithRawResponse.GetContext(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get installed packages by language
func (c *Client) GetPythonPackages(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.Response, error) {
	response, err := c.WithRawResponse.GetPythonPackages(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get installed packages by language
func (c *Client) GetNodejsPackages(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.Response, error) {
	response, err := c.WithRawResponse.GetNodejsPackages(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
