// Code generated by Fern. DO NOT EDIT.

package browser

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
	io "io"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get information about browser, like cdp url, viewport size, etc.
func (c *Client) GetInfo(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseBrowserInfoResult, error) {
	response, err := c.WithRawResponse.GetInfo(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Take a screenshot of the current display.
//
// Returns:
//
//	StreamingResponse: PNG image data with proper headers including display and screenshot dimensions
func (c *Client) Screenshot(
	ctx context.Context,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Screenshot(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Execute a validated action on the current display.
func (c *Client) ExecuteAction(
	ctx context.Context,
	request *sandboxsdkgo.Action,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ActionResponse, error) {
	response, err := c.WithRawResponse.ExecuteAction(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
