// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	big "math/big"
)

var (
	jupyterExecuteRequestFieldCode       = big.NewInt(1 << 0)
	jupyterExecuteRequestFieldTimeout    = big.NewInt(1 << 1)
	jupyterExecuteRequestFieldKernelName = big.NewInt(1 << 2)
	jupyterExecuteRequestFieldSessionId  = big.NewInt(1 << 3)
)

type JupyterExecuteRequest struct {
	// Python code to execute
	Code string `json:"code" url:"-"`
	// Execution timeout in seconds
	Timeout *int `json:"timeout,omitempty" url:"-"`
	// Kernel name to use (e.g., 'python3', 'python3.11'). Defaults to 'python3'
	KernelName *string `json:"kernel_name,omitempty" url:"-"`
	// Session ID to maintain kernel state across requests
	SessionId *string `json:"session_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (j *JupyterExecuteRequest) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteRequest) SetCode(code string) {
	j.Code = code
	j.require(jupyterExecuteRequestFieldCode)
}

// SetTimeout sets the Timeout field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteRequest) SetTimeout(timeout *int) {
	j.Timeout = timeout
	j.require(jupyterExecuteRequestFieldTimeout)
}

// SetKernelName sets the KernelName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteRequest) SetKernelName(kernelName *string) {
	j.KernelName = kernelName
	j.require(jupyterExecuteRequestFieldKernelName)
}

// SetSessionId sets the SessionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteRequest) SetSessionId(sessionId *string) {
	j.SessionId = sessionId
	j.require(jupyterExecuteRequestFieldSessionId)
}

// Active sessions result
var (
	activeSessionsResultFieldSessions = big.NewInt(1 << 0)
)

type ActiveSessionsResult struct {
	// Map of session ID to session info
	Sessions map[string]*SessionInfo `json:"sessions" url:"sessions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *ActiveSessionsResult) GetSessions() map[string]*SessionInfo {
	if a == nil {
		return nil
	}
	return a.Sessions
}

func (a *ActiveSessionsResult) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *ActiveSessionsResult) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSessions sets the Sessions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ActiveSessionsResult) SetSessions(sessions map[string]*SessionInfo) {
	a.Sessions = sessions
	a.require(activeSessionsResultFieldSessions)
}

func (a *ActiveSessionsResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ActiveSessionsResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = ActiveSessionsResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *ActiveSessionsResult) MarshalJSON() ([]byte, error) {
	type embed ActiveSessionsResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *ActiveSessionsResult) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Jupyter code execution response model
var (
	jupyterExecuteResponseFieldKernelName     = big.NewInt(1 << 0)
	jupyterExecuteResponseFieldSessionId      = big.NewInt(1 << 1)
	jupyterExecuteResponseFieldStatus         = big.NewInt(1 << 2)
	jupyterExecuteResponseFieldExecutionCount = big.NewInt(1 << 3)
	jupyterExecuteResponseFieldOutputs        = big.NewInt(1 << 4)
	jupyterExecuteResponseFieldCode           = big.NewInt(1 << 5)
	jupyterExecuteResponseFieldMsgId          = big.NewInt(1 << 6)
)

type JupyterExecuteResponse struct {
	// Name of the kernel used for execution
	KernelName string `json:"kernel_name" url:"kernel_name"`
	// Session ID for this kernel instance
	SessionId string `json:"session_id" url:"session_id"`
	// Execution status: ok, error, or timeout
	Status string `json:"status" url:"status"`
	// Execution count from the kernel
	ExecutionCount *int `json:"execution_count,omitempty" url:"execution_count,omitempty"`
	// List of execution outputs
	Outputs []*JupyterOutput `json:"outputs" url:"outputs"`
	// The executed code
	Code string `json:"code" url:"code"`
	// Message ID from Jupyter kernel
	MsgId *string `json:"msg_id,omitempty" url:"msg_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JupyterExecuteResponse) GetKernelName() string {
	if j == nil {
		return ""
	}
	return j.KernelName
}

func (j *JupyterExecuteResponse) GetSessionId() string {
	if j == nil {
		return ""
	}
	return j.SessionId
}

func (j *JupyterExecuteResponse) GetStatus() string {
	if j == nil {
		return ""
	}
	return j.Status
}

func (j *JupyterExecuteResponse) GetExecutionCount() *int {
	if j == nil {
		return nil
	}
	return j.ExecutionCount
}

func (j *JupyterExecuteResponse) GetOutputs() []*JupyterOutput {
	if j == nil {
		return nil
	}
	return j.Outputs
}

func (j *JupyterExecuteResponse) GetCode() string {
	if j == nil {
		return ""
	}
	return j.Code
}

func (j *JupyterExecuteResponse) GetMsgId() *string {
	if j == nil {
		return nil
	}
	return j.MsgId
}

func (j *JupyterExecuteResponse) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JupyterExecuteResponse) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetKernelName sets the KernelName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetKernelName(kernelName string) {
	j.KernelName = kernelName
	j.require(jupyterExecuteResponseFieldKernelName)
}

// SetSessionId sets the SessionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetSessionId(sessionId string) {
	j.SessionId = sessionId
	j.require(jupyterExecuteResponseFieldSessionId)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetStatus(status string) {
	j.Status = status
	j.require(jupyterExecuteResponseFieldStatus)
}

// SetExecutionCount sets the ExecutionCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetExecutionCount(executionCount *int) {
	j.ExecutionCount = executionCount
	j.require(jupyterExecuteResponseFieldExecutionCount)
}

// SetOutputs sets the Outputs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetOutputs(outputs []*JupyterOutput) {
	j.Outputs = outputs
	j.require(jupyterExecuteResponseFieldOutputs)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetCode(code string) {
	j.Code = code
	j.require(jupyterExecuteResponseFieldCode)
}

// SetMsgId sets the MsgId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterExecuteResponse) SetMsgId(msgId *string) {
	j.MsgId = msgId
	j.require(jupyterExecuteResponseFieldMsgId)
}

func (j *JupyterExecuteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler JupyterExecuteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JupyterExecuteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JupyterExecuteResponse) MarshalJSON() ([]byte, error) {
	type embed JupyterExecuteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*j),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, j.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (j *JupyterExecuteResponse) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

// Jupyter service information response model
var (
	jupyterInfoResponseFieldDefaultKernel         = big.NewInt(1 << 0)
	jupyterInfoResponseFieldAvailableKernels      = big.NewInt(1 << 1)
	jupyterInfoResponseFieldActiveSessions        = big.NewInt(1 << 2)
	jupyterInfoResponseFieldSessionTimeoutSeconds = big.NewInt(1 << 3)
	jupyterInfoResponseFieldMaxSessions           = big.NewInt(1 << 4)
	jupyterInfoResponseFieldDescription           = big.NewInt(1 << 5)
	jupyterInfoResponseFieldKernelDetection       = big.NewInt(1 << 6)
)

type JupyterInfoResponse struct {
	// Default kernel name
	DefaultKernel string `json:"default_kernel" url:"default_kernel"`
	// List of available kernel names
	AvailableKernels []string `json:"available_kernels" url:"available_kernels"`
	// Number of active sessions
	ActiveSessions int `json:"active_sessions" url:"active_sessions"`
	// Session timeout in seconds
	SessionTimeoutSeconds int `json:"session_timeout_seconds" url:"session_timeout_seconds"`
	// Maximum number of concurrent sessions
	MaxSessions int `json:"max_sessions" url:"max_sessions"`
	// Service description
	Description string `json:"description" url:"description"`
	// Kernel detection strategy
	KernelDetection string `json:"kernel_detection" url:"kernel_detection"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JupyterInfoResponse) GetDefaultKernel() string {
	if j == nil {
		return ""
	}
	return j.DefaultKernel
}

func (j *JupyterInfoResponse) GetAvailableKernels() []string {
	if j == nil {
		return nil
	}
	return j.AvailableKernels
}

func (j *JupyterInfoResponse) GetActiveSessions() int {
	if j == nil {
		return 0
	}
	return j.ActiveSessions
}

func (j *JupyterInfoResponse) GetSessionTimeoutSeconds() int {
	if j == nil {
		return 0
	}
	return j.SessionTimeoutSeconds
}

func (j *JupyterInfoResponse) GetMaxSessions() int {
	if j == nil {
		return 0
	}
	return j.MaxSessions
}

func (j *JupyterInfoResponse) GetDescription() string {
	if j == nil {
		return ""
	}
	return j.Description
}

func (j *JupyterInfoResponse) GetKernelDetection() string {
	if j == nil {
		return ""
	}
	return j.KernelDetection
}

func (j *JupyterInfoResponse) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JupyterInfoResponse) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetDefaultKernel sets the DefaultKernel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetDefaultKernel(defaultKernel string) {
	j.DefaultKernel = defaultKernel
	j.require(jupyterInfoResponseFieldDefaultKernel)
}

// SetAvailableKernels sets the AvailableKernels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetAvailableKernels(availableKernels []string) {
	j.AvailableKernels = availableKernels
	j.require(jupyterInfoResponseFieldAvailableKernels)
}

// SetActiveSessions sets the ActiveSessions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetActiveSessions(activeSessions int) {
	j.ActiveSessions = activeSessions
	j.require(jupyterInfoResponseFieldActiveSessions)
}

// SetSessionTimeoutSeconds sets the SessionTimeoutSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetSessionTimeoutSeconds(sessionTimeoutSeconds int) {
	j.SessionTimeoutSeconds = sessionTimeoutSeconds
	j.require(jupyterInfoResponseFieldSessionTimeoutSeconds)
}

// SetMaxSessions sets the MaxSessions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetMaxSessions(maxSessions int) {
	j.MaxSessions = maxSessions
	j.require(jupyterInfoResponseFieldMaxSessions)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetDescription(description string) {
	j.Description = description
	j.require(jupyterInfoResponseFieldDescription)
}

// SetKernelDetection sets the KernelDetection field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterInfoResponse) SetKernelDetection(kernelDetection string) {
	j.KernelDetection = kernelDetection
	j.require(jupyterInfoResponseFieldKernelDetection)
}

func (j *JupyterInfoResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler JupyterInfoResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JupyterInfoResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JupyterInfoResponse) MarshalJSON() ([]byte, error) {
	type embed JupyterInfoResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*j),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, j.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (j *JupyterInfoResponse) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

// Jupyter execution output model
var (
	jupyterOutputFieldOutputType     = big.NewInt(1 << 0)
	jupyterOutputFieldName           = big.NewInt(1 << 1)
	jupyterOutputFieldText           = big.NewInt(1 << 2)
	jupyterOutputFieldData           = big.NewInt(1 << 3)
	jupyterOutputFieldMetadata       = big.NewInt(1 << 4)
	jupyterOutputFieldExecutionCount = big.NewInt(1 << 5)
	jupyterOutputFieldEname          = big.NewInt(1 << 6)
	jupyterOutputFieldEvalue         = big.NewInt(1 << 7)
	jupyterOutputFieldTraceback      = big.NewInt(1 << 8)
)

type JupyterOutput struct {
	// Type of output: stream, execute_result, display_data, or error
	OutputType string `json:"output_type" url:"output_type"`
	// Stream name (stdout/stderr) for stream outputs
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Text content for stream outputs
	Text *string `json:"text,omitempty" url:"text,omitempty"`
	// Output data for execute_result/display_data
	Data map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`
	// Output metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Execution count for execute_result
	ExecutionCount *int `json:"execution_count,omitempty" url:"execution_count,omitempty"`
	// Error name for error outputs
	Ename *string `json:"ename,omitempty" url:"ename,omitempty"`
	// Error value for error outputs
	Evalue *string `json:"evalue,omitempty" url:"evalue,omitempty"`
	// Error traceback for error outputs
	Traceback []string `json:"traceback,omitempty" url:"traceback,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JupyterOutput) GetOutputType() string {
	if j == nil {
		return ""
	}
	return j.OutputType
}

func (j *JupyterOutput) GetName() *string {
	if j == nil {
		return nil
	}
	return j.Name
}

func (j *JupyterOutput) GetText() *string {
	if j == nil {
		return nil
	}
	return j.Text
}

func (j *JupyterOutput) GetData() map[string]interface{} {
	if j == nil {
		return nil
	}
	return j.Data
}

func (j *JupyterOutput) GetMetadata() map[string]interface{} {
	if j == nil {
		return nil
	}
	return j.Metadata
}

func (j *JupyterOutput) GetExecutionCount() *int {
	if j == nil {
		return nil
	}
	return j.ExecutionCount
}

func (j *JupyterOutput) GetEname() *string {
	if j == nil {
		return nil
	}
	return j.Ename
}

func (j *JupyterOutput) GetEvalue() *string {
	if j == nil {
		return nil
	}
	return j.Evalue
}

func (j *JupyterOutput) GetTraceback() []string {
	if j == nil {
		return nil
	}
	return j.Traceback
}

func (j *JupyterOutput) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JupyterOutput) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetOutputType sets the OutputType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetOutputType(outputType string) {
	j.OutputType = outputType
	j.require(jupyterOutputFieldOutputType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetName(name *string) {
	j.Name = name
	j.require(jupyterOutputFieldName)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetText(text *string) {
	j.Text = text
	j.require(jupyterOutputFieldText)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetData(data map[string]interface{}) {
	j.Data = data
	j.require(jupyterOutputFieldData)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetMetadata(metadata map[string]interface{}) {
	j.Metadata = metadata
	j.require(jupyterOutputFieldMetadata)
}

// SetExecutionCount sets the ExecutionCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetExecutionCount(executionCount *int) {
	j.ExecutionCount = executionCount
	j.require(jupyterOutputFieldExecutionCount)
}

// SetEname sets the Ename field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetEname(ename *string) {
	j.Ename = ename
	j.require(jupyterOutputFieldEname)
}

// SetEvalue sets the Evalue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetEvalue(evalue *string) {
	j.Evalue = evalue
	j.require(jupyterOutputFieldEvalue)
}

// SetTraceback sets the Traceback field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JupyterOutput) SetTraceback(traceback []string) {
	j.Traceback = traceback
	j.require(jupyterOutputFieldTraceback)
}

func (j *JupyterOutput) UnmarshalJSON(data []byte) error {
	type unmarshaler JupyterOutput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JupyterOutput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JupyterOutput) MarshalJSON() ([]byte, error) {
	type embed JupyterOutput
	var marshaler = struct {
		embed
	}{
		embed: embed(*j),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, j.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (j *JupyterOutput) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

var (
	responseActiveSessionsResultFieldSuccess = big.NewInt(1 << 0)
	responseActiveSessionsResultFieldMessage = big.NewInt(1 << 1)
	responseActiveSessionsResultFieldData    = big.NewInt(1 << 2)
)

type ResponseActiveSessionsResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ActiveSessionsResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseActiveSessionsResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseActiveSessionsResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseActiveSessionsResult) GetData() *ActiveSessionsResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseActiveSessionsResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseActiveSessionsResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseActiveSessionsResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseActiveSessionsResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseActiveSessionsResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseActiveSessionsResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseActiveSessionsResult) SetData(data *ActiveSessionsResult) {
	r.Data = data
	r.require(responseActiveSessionsResultFieldData)
}

func (r *ResponseActiveSessionsResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseActiveSessionsResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseActiveSessionsResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseActiveSessionsResult) MarshalJSON() ([]byte, error) {
	type embed ResponseActiveSessionsResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseActiveSessionsResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseJupyterExecuteResponseFieldSuccess = big.NewInt(1 << 0)
	responseJupyterExecuteResponseFieldMessage = big.NewInt(1 << 1)
	responseJupyterExecuteResponseFieldData    = big.NewInt(1 << 2)
)

type ResponseJupyterExecuteResponse struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *JupyterExecuteResponse `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseJupyterExecuteResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseJupyterExecuteResponse) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseJupyterExecuteResponse) GetData() *JupyterExecuteResponse {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseJupyterExecuteResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseJupyterExecuteResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseJupyterExecuteResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseJupyterExecuteResponseFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseJupyterExecuteResponse) SetMessage(message *string) {
	r.Message = message
	r.require(responseJupyterExecuteResponseFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseJupyterExecuteResponse) SetData(data *JupyterExecuteResponse) {
	r.Data = data
	r.require(responseJupyterExecuteResponseFieldData)
}

func (r *ResponseJupyterExecuteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseJupyterExecuteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseJupyterExecuteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseJupyterExecuteResponse) MarshalJSON() ([]byte, error) {
	type embed ResponseJupyterExecuteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseJupyterExecuteResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseJupyterInfoResponseFieldSuccess = big.NewInt(1 << 0)
	responseJupyterInfoResponseFieldMessage = big.NewInt(1 << 1)
	responseJupyterInfoResponseFieldData    = big.NewInt(1 << 2)
)

type ResponseJupyterInfoResponse struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *JupyterInfoResponse `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseJupyterInfoResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseJupyterInfoResponse) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseJupyterInfoResponse) GetData() *JupyterInfoResponse {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseJupyterInfoResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseJupyterInfoResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseJupyterInfoResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseJupyterInfoResponseFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseJupyterInfoResponse) SetMessage(message *string) {
	r.Message = message
	r.require(responseJupyterInfoResponseFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseJupyterInfoResponse) SetData(data *JupyterInfoResponse) {
	r.Data = data
	r.require(responseJupyterInfoResponseFieldData)
}

func (r *ResponseJupyterInfoResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseJupyterInfoResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseJupyterInfoResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseJupyterInfoResponse) MarshalJSON() ([]byte, error) {
	type embed ResponseJupyterInfoResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseJupyterInfoResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Active session information
var (
	sessionInfoFieldKernelName = big.NewInt(1 << 0)
	sessionInfoFieldLastUsed   = big.NewInt(1 << 1)
	sessionInfoFieldAgeSeconds = big.NewInt(1 << 2)
)

type SessionInfo struct {
	// Kernel name
	KernelName string `json:"kernel_name" url:"kernel_name"`
	// Last used timestamp
	LastUsed float64 `json:"last_used" url:"last_used"`
	// Age of session in seconds
	AgeSeconds int `json:"age_seconds" url:"age_seconds"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SessionInfo) GetKernelName() string {
	if s == nil {
		return ""
	}
	return s.KernelName
}

func (s *SessionInfo) GetLastUsed() float64 {
	if s == nil {
		return 0
	}
	return s.LastUsed
}

func (s *SessionInfo) GetAgeSeconds() int {
	if s == nil {
		return 0
	}
	return s.AgeSeconds
}

func (s *SessionInfo) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SessionInfo) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetKernelName sets the KernelName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionInfo) SetKernelName(kernelName string) {
	s.KernelName = kernelName
	s.require(sessionInfoFieldKernelName)
}

// SetLastUsed sets the LastUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionInfo) SetLastUsed(lastUsed float64) {
	s.LastUsed = lastUsed
	s.require(sessionInfoFieldLastUsed)
}

// SetAgeSeconds sets the AgeSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SessionInfo) SetAgeSeconds(ageSeconds int) {
	s.AgeSeconds = ageSeconds
	s.require(sessionInfoFieldAgeSeconds)
}

func (s *SessionInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SessionInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SessionInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SessionInfo) MarshalJSON() ([]byte, error) {
	type embed SessionInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SessionInfo) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
