// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	big "math/big"
)

var (
	sandboxResponseFieldSuccess = big.NewInt(1 << 0)
	sandboxResponseFieldMessage = big.NewInt(1 << 1)
	sandboxResponseFieldData    = big.NewInt(1 << 2)
	sandboxResponseFieldHomeDir = big.NewInt(1 << 3)
	sandboxResponseFieldVersion = big.NewInt(1 << 4)
)

type SandboxResponse struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data    interface{} `json:"data,omitempty" url:"data,omitempty"`
	HomeDir string      `json:"home_dir" url:"home_dir"`
	Version string      `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SandboxResponse) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

func (s *SandboxResponse) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

func (s *SandboxResponse) GetData() interface{} {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SandboxResponse) GetHomeDir() string {
	if s == nil {
		return ""
	}
	return s.HomeDir
}

func (s *SandboxResponse) GetVersion() string {
	if s == nil {
		return ""
	}
	return s.Version
}

func (s *SandboxResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SandboxResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SandboxResponse) SetSuccess(success *bool) {
	s.Success = success
	s.require(sandboxResponseFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SandboxResponse) SetMessage(message *string) {
	s.Message = message
	s.require(sandboxResponseFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SandboxResponse) SetData(data interface{}) {
	s.Data = data
	s.require(sandboxResponseFieldData)
}

// SetHomeDir sets the HomeDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SandboxResponse) SetHomeDir(homeDir string) {
	s.HomeDir = homeDir
	s.require(sandboxResponseFieldHomeDir)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SandboxResponse) SetVersion(version string) {
	s.Version = version
	s.require(sandboxResponseFieldVersion)
}

func (s *SandboxResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SandboxResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SandboxResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SandboxResponse) MarshalJSON() ([]byte, error) {
	type embed SandboxResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SandboxResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
