// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	shellCreateSessionRequestFieldId      = big.NewInt(1 << 0)
	shellCreateSessionRequestFieldExecDir = big.NewInt(1 << 1)
)

type ShellCreateSessionRequest struct {
	// Unique identifier for the shell session, auto-generated if not provided
	Id *string `json:"id,omitempty" url:"-"`
	// Working directory for the new session (must use absolute path)
	ExecDir *string `json:"exec_dir,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShellCreateSessionRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCreateSessionRequest) SetId(id *string) {
	s.Id = id
	s.require(shellCreateSessionRequestFieldId)
}

// SetExecDir sets the ExecDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCreateSessionRequest) SetExecDir(execDir *string) {
	s.ExecDir = execDir
	s.require(shellCreateSessionRequestFieldExecDir)
}

var (
	shellExecRequestFieldId        = big.NewInt(1 << 0)
	shellExecRequestFieldExecDir   = big.NewInt(1 << 1)
	shellExecRequestFieldCommand   = big.NewInt(1 << 2)
	shellExecRequestFieldAsyncMode = big.NewInt(1 << 3)
)

type ShellExecRequest struct {
	// Unique identifier of the target shell session, if not provided, one will be automatically created
	Id *string `json:"id,omitempty" url:"-"`
	// Working directory for command execution (must use absolute path)
	ExecDir *string `json:"exec_dir,omitempty" url:"-"`
	// Shell command to execute
	Command string `json:"command" url:"-"`
	// Whether to execute command asynchronously (default: False for async, False for synchronous execution)
	AsyncMode *bool `json:"async_mode,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShellExecRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellExecRequest) SetId(id *string) {
	s.Id = id
	s.require(shellExecRequestFieldId)
}

// SetExecDir sets the ExecDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellExecRequest) SetExecDir(execDir *string) {
	s.ExecDir = execDir
	s.require(shellExecRequestFieldExecDir)
}

// SetCommand sets the Command field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellExecRequest) SetCommand(command string) {
	s.Command = command
	s.require(shellExecRequestFieldCommand)
}

// SetAsyncMode sets the AsyncMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellExecRequest) SetAsyncMode(asyncMode *bool) {
	s.AsyncMode = asyncMode
	s.require(shellExecRequestFieldAsyncMode)
}

var (
	shellKillProcessRequestFieldId = big.NewInt(1 << 0)
)

type ShellKillProcessRequest struct {
	// Unique identifier of the target shell session
	Id string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShellKillProcessRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellKillProcessRequest) SetId(id string) {
	s.Id = id
	s.require(shellKillProcessRequestFieldId)
}

// Active shell sessions result
var (
	activeShellSessionsResultFieldSessions = big.NewInt(1 << 0)
)

type ActiveShellSessionsResult struct {
	// Map of session ID to session info
	Sessions map[string]*ShellSessionInfo `json:"sessions" url:"sessions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *ActiveShellSessionsResult) GetSessions() map[string]*ShellSessionInfo {
	if a == nil {
		return nil
	}
	return a.Sessions
}

func (a *ActiveShellSessionsResult) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *ActiveShellSessionsResult) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSessions sets the Sessions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ActiveShellSessionsResult) SetSessions(sessions map[string]*ShellSessionInfo) {
	a.Sessions = sessions
	a.require(activeShellSessionsResultFieldSessions)
}

func (a *ActiveShellSessionsResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ActiveShellSessionsResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = ActiveShellSessionsResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *ActiveShellSessionsResult) MarshalJSON() ([]byte, error) {
	type embed ActiveShellSessionsResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *ActiveShellSessionsResult) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Shell command execution status (compatible with OpenHands)
type BashCommandStatus string

const (
	BashCommandStatusRunning         BashCommandStatus = "running"
	BashCommandStatusCompleted       BashCommandStatus = "completed"
	BashCommandStatusNoChangeTimeout BashCommandStatus = "no_change_timeout"
	BashCommandStatusHardTimeout     BashCommandStatus = "hard_timeout"
	BashCommandStatusTerminated      BashCommandStatus = "terminated"
)

func NewBashCommandStatusFromString(s string) (BashCommandStatus, error) {
	switch s {
	case "running":
		return BashCommandStatusRunning, nil
	case "completed":
		return BashCommandStatusCompleted, nil
	case "no_change_timeout":
		return BashCommandStatusNoChangeTimeout, nil
	case "hard_timeout":
		return BashCommandStatusHardTimeout, nil
	case "terminated":
		return BashCommandStatusTerminated, nil
	}
	var t BashCommandStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (b BashCommandStatus) Ptr() *BashCommandStatus {
	return &b
}

// Shell command console record model
var (
	consoleRecordFieldPs1     = big.NewInt(1 << 0)
	consoleRecordFieldCommand = big.NewInt(1 << 1)
	consoleRecordFieldOutput  = big.NewInt(1 << 2)
)

type ConsoleRecord struct {
	// Command prompt
	Ps1 string `json:"ps1" url:"ps1"`
	// Executed command
	Command string `json:"command" url:"command"`
	// Command output
	Output *string `json:"output,omitempty" url:"output,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConsoleRecord) GetPs1() string {
	if c == nil {
		return ""
	}
	return c.Ps1
}

func (c *ConsoleRecord) GetCommand() string {
	if c == nil {
		return ""
	}
	return c.Command
}

func (c *ConsoleRecord) GetOutput() *string {
	if c == nil {
		return nil
	}
	return c.Output
}

func (c *ConsoleRecord) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ConsoleRecord) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPs1 sets the Ps1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsoleRecord) SetPs1(ps1 string) {
	c.Ps1 = ps1
	c.require(consoleRecordFieldPs1)
}

// SetCommand sets the Command field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsoleRecord) SetCommand(command string) {
	c.Command = command
	c.require(consoleRecordFieldCommand)
}

// SetOutput sets the Output field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsoleRecord) SetOutput(output *string) {
	c.Output = output
	c.require(consoleRecordFieldOutput)
}

func (c *ConsoleRecord) UnmarshalJSON(data []byte) error {
	type unmarshaler ConsoleRecord
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConsoleRecord(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConsoleRecord) MarshalJSON() ([]byte, error) {
	type embed ConsoleRecord
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConsoleRecord) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	responseActiveShellSessionsResultFieldSuccess = big.NewInt(1 << 0)
	responseActiveShellSessionsResultFieldMessage = big.NewInt(1 << 1)
	responseActiveShellSessionsResultFieldData    = big.NewInt(1 << 2)
)

type ResponseActiveShellSessionsResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ActiveShellSessionsResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseActiveShellSessionsResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseActiveShellSessionsResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseActiveShellSessionsResult) GetData() *ActiveShellSessionsResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseActiveShellSessionsResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseActiveShellSessionsResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseActiveShellSessionsResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseActiveShellSessionsResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseActiveShellSessionsResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseActiveShellSessionsResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseActiveShellSessionsResult) SetData(data *ActiveShellSessionsResult) {
	r.Data = data
	r.require(responseActiveShellSessionsResultFieldData)
}

func (r *ResponseActiveShellSessionsResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseActiveShellSessionsResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseActiveShellSessionsResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseActiveShellSessionsResult) MarshalJSON() ([]byte, error) {
	type embed ResponseActiveShellSessionsResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseActiveShellSessionsResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseShellCommandResultFieldSuccess = big.NewInt(1 << 0)
	responseShellCommandResultFieldMessage = big.NewInt(1 << 1)
	responseShellCommandResultFieldData    = big.NewInt(1 << 2)
)

type ResponseShellCommandResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ShellCommandResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseShellCommandResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseShellCommandResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseShellCommandResult) GetData() *ShellCommandResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseShellCommandResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseShellCommandResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellCommandResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseShellCommandResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellCommandResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseShellCommandResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellCommandResult) SetData(data *ShellCommandResult) {
	r.Data = data
	r.require(responseShellCommandResultFieldData)
}

func (r *ResponseShellCommandResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseShellCommandResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseShellCommandResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseShellCommandResult) MarshalJSON() ([]byte, error) {
	type embed ResponseShellCommandResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseShellCommandResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseShellCreateSessionResponseFieldSuccess = big.NewInt(1 << 0)
	responseShellCreateSessionResponseFieldMessage = big.NewInt(1 << 1)
	responseShellCreateSessionResponseFieldData    = big.NewInt(1 << 2)
)

type ResponseShellCreateSessionResponse struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ShellCreateSessionResponse `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseShellCreateSessionResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseShellCreateSessionResponse) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseShellCreateSessionResponse) GetData() *ShellCreateSessionResponse {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseShellCreateSessionResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseShellCreateSessionResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellCreateSessionResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseShellCreateSessionResponseFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellCreateSessionResponse) SetMessage(message *string) {
	r.Message = message
	r.require(responseShellCreateSessionResponseFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellCreateSessionResponse) SetData(data *ShellCreateSessionResponse) {
	r.Data = data
	r.require(responseShellCreateSessionResponseFieldData)
}

func (r *ResponseShellCreateSessionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseShellCreateSessionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseShellCreateSessionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseShellCreateSessionResponse) MarshalJSON() ([]byte, error) {
	type embed ResponseShellCreateSessionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseShellCreateSessionResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseShellKillResultFieldSuccess = big.NewInt(1 << 0)
	responseShellKillResultFieldMessage = big.NewInt(1 << 1)
	responseShellKillResultFieldData    = big.NewInt(1 << 2)
)

type ResponseShellKillResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ShellKillResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseShellKillResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseShellKillResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseShellKillResult) GetData() *ShellKillResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseShellKillResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseShellKillResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellKillResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseShellKillResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellKillResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseShellKillResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellKillResult) SetData(data *ShellKillResult) {
	r.Data = data
	r.require(responseShellKillResultFieldData)
}

func (r *ResponseShellKillResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseShellKillResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseShellKillResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseShellKillResult) MarshalJSON() ([]byte, error) {
	type embed ResponseShellKillResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseShellKillResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseShellViewResultFieldSuccess = big.NewInt(1 << 0)
	responseShellViewResultFieldMessage = big.NewInt(1 << 1)
	responseShellViewResultFieldData    = big.NewInt(1 << 2)
)

type ResponseShellViewResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ShellViewResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseShellViewResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseShellViewResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseShellViewResult) GetData() *ShellViewResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseShellViewResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseShellViewResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellViewResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseShellViewResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellViewResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseShellViewResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellViewResult) SetData(data *ShellViewResult) {
	r.Data = data
	r.require(responseShellViewResultFieldData)
}

func (r *ResponseShellViewResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseShellViewResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseShellViewResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseShellViewResult) MarshalJSON() ([]byte, error) {
	type embed ResponseShellViewResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseShellViewResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseShellWaitResultFieldSuccess = big.NewInt(1 << 0)
	responseShellWaitResultFieldMessage = big.NewInt(1 << 1)
	responseShellWaitResultFieldData    = big.NewInt(1 << 2)
)

type ResponseShellWaitResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ShellWaitResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseShellWaitResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseShellWaitResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseShellWaitResult) GetData() *ShellWaitResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseShellWaitResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseShellWaitResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellWaitResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseShellWaitResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellWaitResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseShellWaitResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellWaitResult) SetData(data *ShellWaitResult) {
	r.Data = data
	r.require(responseShellWaitResultFieldData)
}

func (r *ResponseShellWaitResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseShellWaitResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseShellWaitResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseShellWaitResult) MarshalJSON() ([]byte, error) {
	type embed ResponseShellWaitResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseShellWaitResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseShellWriteResultFieldSuccess = big.NewInt(1 << 0)
	responseShellWriteResultFieldMessage = big.NewInt(1 << 1)
	responseShellWriteResultFieldData    = big.NewInt(1 << 2)
)

type ResponseShellWriteResult struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *ShellWriteResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseShellWriteResult) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseShellWriteResult) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseShellWriteResult) GetData() *ShellWriteResult {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseShellWriteResult) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseShellWriteResult) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellWriteResult) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseShellWriteResultFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellWriteResult) SetMessage(message *string) {
	r.Message = message
	r.require(responseShellWriteResultFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseShellWriteResult) SetData(data *ShellWriteResult) {
	r.Data = data
	r.require(responseShellWriteResultFieldData)
}

func (r *ResponseShellWriteResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseShellWriteResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseShellWriteResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseShellWriteResult) MarshalJSON() ([]byte, error) {
	type embed ResponseShellWriteResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseShellWriteResult) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	responseStrFieldSuccess = big.NewInt(1 << 0)
	responseStrFieldMessage = big.NewInt(1 << 1)
	responseStrFieldData    = big.NewInt(1 << 2)
)

type ResponseStr struct {
	// Whether the operation was successful
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Operation result message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Data returned from the operation
	Data *string `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResponseStr) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *ResponseStr) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ResponseStr) GetData() *string {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResponseStr) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResponseStr) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseStr) SetSuccess(success *bool) {
	r.Success = success
	r.require(responseStrFieldSuccess)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseStr) SetMessage(message *string) {
	r.Message = message
	r.require(responseStrFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResponseStr) SetData(data *string) {
	r.Data = data
	r.require(responseStrFieldData)
}

func (r *ResponseStr) UnmarshalJSON(data []byte) error {
	type unmarshaler ResponseStr
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResponseStr(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResponseStr) MarshalJSON() ([]byte, error) {
	type embed ResponseStr
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResponseStr) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Shell command execution result model
var (
	shellCommandResultFieldSessionId = big.NewInt(1 << 0)
	shellCommandResultFieldCommand   = big.NewInt(1 << 1)
	shellCommandResultFieldStatus    = big.NewInt(1 << 2)
	shellCommandResultFieldOutput    = big.NewInt(1 << 3)
	shellCommandResultFieldConsole   = big.NewInt(1 << 4)
	shellCommandResultFieldExitCode  = big.NewInt(1 << 5)
)

type ShellCommandResult struct {
	// Shell session ID
	SessionId string `json:"session_id" url:"session_id"`
	// Executed command
	Command string `json:"command" url:"command"`
	// Command execution status
	Status BashCommandStatus `json:"status" url:"status"`
	// Command execution output, only has value when status is completed
	Output *string `json:"output,omitempty" url:"output,omitempty"`
	// Console command records
	Console []*ConsoleRecord `json:"console,omitempty" url:"console,omitempty"`
	// Command execution exit code, only has value when status is completed
	ExitCode *int `json:"exit_code,omitempty" url:"exit_code,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellCommandResult) GetSessionId() string {
	if s == nil {
		return ""
	}
	return s.SessionId
}

func (s *ShellCommandResult) GetCommand() string {
	if s == nil {
		return ""
	}
	return s.Command
}

func (s *ShellCommandResult) GetStatus() BashCommandStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShellCommandResult) GetOutput() *string {
	if s == nil {
		return nil
	}
	return s.Output
}

func (s *ShellCommandResult) GetConsole() []*ConsoleRecord {
	if s == nil {
		return nil
	}
	return s.Console
}

func (s *ShellCommandResult) GetExitCode() *int {
	if s == nil {
		return nil
	}
	return s.ExitCode
}

func (s *ShellCommandResult) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellCommandResult) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSessionId sets the SessionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCommandResult) SetSessionId(sessionId string) {
	s.SessionId = sessionId
	s.require(shellCommandResultFieldSessionId)
}

// SetCommand sets the Command field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCommandResult) SetCommand(command string) {
	s.Command = command
	s.require(shellCommandResultFieldCommand)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCommandResult) SetStatus(status BashCommandStatus) {
	s.Status = status
	s.require(shellCommandResultFieldStatus)
}

// SetOutput sets the Output field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCommandResult) SetOutput(output *string) {
	s.Output = output
	s.require(shellCommandResultFieldOutput)
}

// SetConsole sets the Console field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCommandResult) SetConsole(console []*ConsoleRecord) {
	s.Console = console
	s.require(shellCommandResultFieldConsole)
}

// SetExitCode sets the ExitCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCommandResult) SetExitCode(exitCode *int) {
	s.ExitCode = exitCode
	s.require(shellCommandResultFieldExitCode)
}

func (s *ShellCommandResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ShellCommandResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShellCommandResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellCommandResult) MarshalJSON() ([]byte, error) {
	type embed ShellCommandResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellCommandResult) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Shell session creation response model
var (
	shellCreateSessionResponseFieldSessionId  = big.NewInt(1 << 0)
	shellCreateSessionResponseFieldWorkingDir = big.NewInt(1 << 1)
)

type ShellCreateSessionResponse struct {
	// Unique identifier of the created shell session
	SessionId string `json:"session_id" url:"session_id"`
	// Working directory of the created session
	WorkingDir string `json:"working_dir" url:"working_dir"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellCreateSessionResponse) GetSessionId() string {
	if s == nil {
		return ""
	}
	return s.SessionId
}

func (s *ShellCreateSessionResponse) GetWorkingDir() string {
	if s == nil {
		return ""
	}
	return s.WorkingDir
}

func (s *ShellCreateSessionResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellCreateSessionResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSessionId sets the SessionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCreateSessionResponse) SetSessionId(sessionId string) {
	s.SessionId = sessionId
	s.require(shellCreateSessionResponseFieldSessionId)
}

// SetWorkingDir sets the WorkingDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellCreateSessionResponse) SetWorkingDir(workingDir string) {
	s.WorkingDir = workingDir
	s.require(shellCreateSessionResponseFieldWorkingDir)
}

func (s *ShellCreateSessionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ShellCreateSessionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShellCreateSessionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellCreateSessionResponse) MarshalJSON() ([]byte, error) {
	type embed ShellCreateSessionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellCreateSessionResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Process termination result model
var (
	shellKillResultFieldStatus     = big.NewInt(1 << 0)
	shellKillResultFieldReturncode = big.NewInt(1 << 1)
)

type ShellKillResult struct {
	// Process status
	Status BashCommandStatus `json:"status" url:"status"`
	// Process return code
	Returncode int `json:"returncode" url:"returncode"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellKillResult) GetStatus() BashCommandStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShellKillResult) GetReturncode() int {
	if s == nil {
		return 0
	}
	return s.Returncode
}

func (s *ShellKillResult) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellKillResult) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellKillResult) SetStatus(status BashCommandStatus) {
	s.Status = status
	s.require(shellKillResultFieldStatus)
}

// SetReturncode sets the Returncode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellKillResult) SetReturncode(returncode int) {
	s.Returncode = returncode
	s.require(shellKillResultFieldReturncode)
}

func (s *ShellKillResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ShellKillResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShellKillResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellKillResult) MarshalJSON() ([]byte, error) {
	type embed ShellKillResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellKillResult) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Shell session information
var (
	shellSessionInfoFieldWorkingDir     = big.NewInt(1 << 0)
	shellSessionInfoFieldCreatedAt      = big.NewInt(1 << 1)
	shellSessionInfoFieldLastUsedAt     = big.NewInt(1 << 2)
	shellSessionInfoFieldAgeSeconds     = big.NewInt(1 << 3)
	shellSessionInfoFieldStatus         = big.NewInt(1 << 4)
	shellSessionInfoFieldCurrentCommand = big.NewInt(1 << 5)
)

type ShellSessionInfo struct {
	// Working directory
	WorkingDir string `json:"working_dir" url:"working_dir"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Last used timestamp
	LastUsedAt time.Time `json:"last_used_at" url:"last_used_at"`
	// Age of session in seconds
	AgeSeconds int `json:"age_seconds" url:"age_seconds"`
	// Session status
	Status string `json:"status" url:"status"`
	// Currently executing command
	CurrentCommand *string `json:"current_command,omitempty" url:"current_command,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellSessionInfo) GetWorkingDir() string {
	if s == nil {
		return ""
	}
	return s.WorkingDir
}

func (s *ShellSessionInfo) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *ShellSessionInfo) GetLastUsedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.LastUsedAt
}

func (s *ShellSessionInfo) GetAgeSeconds() int {
	if s == nil {
		return 0
	}
	return s.AgeSeconds
}

func (s *ShellSessionInfo) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShellSessionInfo) GetCurrentCommand() *string {
	if s == nil {
		return nil
	}
	return s.CurrentCommand
}

func (s *ShellSessionInfo) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellSessionInfo) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetWorkingDir sets the WorkingDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellSessionInfo) SetWorkingDir(workingDir string) {
	s.WorkingDir = workingDir
	s.require(shellSessionInfoFieldWorkingDir)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellSessionInfo) SetCreatedAt(createdAt time.Time) {
	s.CreatedAt = createdAt
	s.require(shellSessionInfoFieldCreatedAt)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellSessionInfo) SetLastUsedAt(lastUsedAt time.Time) {
	s.LastUsedAt = lastUsedAt
	s.require(shellSessionInfoFieldLastUsedAt)
}

// SetAgeSeconds sets the AgeSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellSessionInfo) SetAgeSeconds(ageSeconds int) {
	s.AgeSeconds = ageSeconds
	s.require(shellSessionInfoFieldAgeSeconds)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellSessionInfo) SetStatus(status string) {
	s.Status = status
	s.require(shellSessionInfoFieldStatus)
}

// SetCurrentCommand sets the CurrentCommand field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellSessionInfo) SetCurrentCommand(currentCommand *string) {
	s.CurrentCommand = currentCommand
	s.require(shellSessionInfoFieldCurrentCommand)
}

func (s *ShellSessionInfo) UnmarshalJSON(data []byte) error {
	type embed ShellSessionInfo
	var unmarshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at"`
		LastUsedAt *internal.DateTime `json:"last_used_at"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = ShellSessionInfo(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	s.LastUsedAt = unmarshaler.LastUsedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellSessionInfo) MarshalJSON() ([]byte, error) {
	type embed ShellSessionInfo
	var marshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at"`
		LastUsedAt *internal.DateTime `json:"last_used_at"`
	}{
		embed:      embed(*s),
		CreatedAt:  internal.NewDateTime(s.CreatedAt),
		LastUsedAt: internal.NewDateTime(s.LastUsedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellSessionInfo) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Shell session content view result model
var (
	shellViewResultFieldOutput    = big.NewInt(1 << 0)
	shellViewResultFieldSessionId = big.NewInt(1 << 1)
	shellViewResultFieldConsole   = big.NewInt(1 << 2)
	shellViewResultFieldStatus    = big.NewInt(1 << 3)
	shellViewResultFieldCommand   = big.NewInt(1 << 4)
	shellViewResultFieldExitCode  = big.NewInt(1 << 5)
)

type ShellViewResult struct {
	// Shell session output content
	Output string `json:"output" url:"output"`
	// Shell session ID
	SessionId string `json:"session_id" url:"session_id"`
	// Console command records
	Console []*ConsoleRecord `json:"console,omitempty" url:"console,omitempty"`
	// Shell session status
	Status BashCommandStatus `json:"status" url:"status"`
	// Last executed or currently executing command
	Command *string `json:"command,omitempty" url:"command,omitempty"`
	// Command execution exit code, only has value when status is completed
	ExitCode *int `json:"exit_code,omitempty" url:"exit_code,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellViewResult) GetOutput() string {
	if s == nil {
		return ""
	}
	return s.Output
}

func (s *ShellViewResult) GetSessionId() string {
	if s == nil {
		return ""
	}
	return s.SessionId
}

func (s *ShellViewResult) GetConsole() []*ConsoleRecord {
	if s == nil {
		return nil
	}
	return s.Console
}

func (s *ShellViewResult) GetStatus() BashCommandStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShellViewResult) GetCommand() *string {
	if s == nil {
		return nil
	}
	return s.Command
}

func (s *ShellViewResult) GetExitCode() *int {
	if s == nil {
		return nil
	}
	return s.ExitCode
}

func (s *ShellViewResult) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellViewResult) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetOutput sets the Output field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewResult) SetOutput(output string) {
	s.Output = output
	s.require(shellViewResultFieldOutput)
}

// SetSessionId sets the SessionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewResult) SetSessionId(sessionId string) {
	s.SessionId = sessionId
	s.require(shellViewResultFieldSessionId)
}

// SetConsole sets the Console field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewResult) SetConsole(console []*ConsoleRecord) {
	s.Console = console
	s.require(shellViewResultFieldConsole)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewResult) SetStatus(status BashCommandStatus) {
	s.Status = status
	s.require(shellViewResultFieldStatus)
}

// SetCommand sets the Command field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewResult) SetCommand(command *string) {
	s.Command = command
	s.require(shellViewResultFieldCommand)
}

// SetExitCode sets the ExitCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewResult) SetExitCode(exitCode *int) {
	s.ExitCode = exitCode
	s.require(shellViewResultFieldExitCode)
}

func (s *ShellViewResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ShellViewResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShellViewResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellViewResult) MarshalJSON() ([]byte, error) {
	type embed ShellViewResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellViewResult) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Process wait result model
var (
	shellWaitResultFieldStatus = big.NewInt(1 << 0)
)

type ShellWaitResult struct {
	// Process status
	Status BashCommandStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellWaitResult) GetStatus() BashCommandStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShellWaitResult) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellWaitResult) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWaitResult) SetStatus(status BashCommandStatus) {
	s.Status = status
	s.require(shellWaitResultFieldStatus)
}

func (s *ShellWaitResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ShellWaitResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShellWaitResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellWaitResult) MarshalJSON() ([]byte, error) {
	type embed ShellWaitResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellWaitResult) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Process input write result model
var (
	shellWriteResultFieldStatus = big.NewInt(1 << 0)
)

type ShellWriteResult struct {
	// Write status
	Status BashCommandStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShellWriteResult) GetStatus() BashCommandStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShellWriteResult) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ShellWriteResult) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWriteResult) SetStatus(status BashCommandStatus) {
	s.Status = status
	s.require(shellWriteResultFieldStatus)
}

func (s *ShellWriteResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ShellWriteResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShellWriteResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShellWriteResult) MarshalJSON() ([]byte, error) {
	type embed ShellWriteResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShellWriteResult) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	shellViewRequestFieldId = big.NewInt(1 << 0)
)

type ShellViewRequest struct {
	// Unique identifier of the target shell session
	Id string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShellViewRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellViewRequest) SetId(id string) {
	s.Id = id
	s.require(shellViewRequestFieldId)
}

var (
	shellWaitRequestFieldId      = big.NewInt(1 << 0)
	shellWaitRequestFieldSeconds = big.NewInt(1 << 1)
)

type ShellWaitRequest struct {
	// Unique identifier of the target shell session
	Id string `json:"id" url:"-"`
	// Wait time (seconds)
	Seconds *int `json:"seconds,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShellWaitRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWaitRequest) SetId(id string) {
	s.Id = id
	s.require(shellWaitRequestFieldId)
}

// SetSeconds sets the Seconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWaitRequest) SetSeconds(seconds *int) {
	s.Seconds = seconds
	s.require(shellWaitRequestFieldSeconds)
}

var (
	shellWriteToProcessRequestFieldId         = big.NewInt(1 << 0)
	shellWriteToProcessRequestFieldInput      = big.NewInt(1 << 1)
	shellWriteToProcessRequestFieldPressEnter = big.NewInt(1 << 2)
)

type ShellWriteToProcessRequest struct {
	// Unique identifier of the target shell session
	Id string `json:"id" url:"-"`
	// Input content to write to the process
	Input string `json:"input" url:"-"`
	// Whether to press enter key after input
	PressEnter bool `json:"press_enter" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShellWriteToProcessRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWriteToProcessRequest) SetId(id string) {
	s.Id = id
	s.require(shellWriteToProcessRequestFieldId)
}

// SetInput sets the Input field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWriteToProcessRequest) SetInput(input string) {
	s.Input = input
	s.require(shellWriteToProcessRequestFieldInput)
}

// SetPressEnter sets the PressEnter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShellWriteToProcessRequest) SetPressEnter(pressEnter bool) {
	s.PressEnter = pressEnter
	s.require(shellWriteToProcessRequestFieldPressEnter)
}
