// Code generated by Fern. DO NOT EDIT.

package code

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Run code through the unified runtime, dispatching to Python, Node.js, or future language executors
func (c *Client) ExecuteCode(
	ctx context.Context,
	request *sandboxsdkgo.CodeExecuteRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseCodeExecuteResponse, error) {
	response, err := c.WithRawResponse.ExecuteCode(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Return metadata about supported code runtimes
func (c *Client) GetInfo(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseCodeInfoResponse, error) {
	response, err := c.WithRawResponse.GetInfo(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
