// Code generated by Fern. DO NOT EDIT.

package jupyter

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Execute Python code using Jupyter kernel with session persistence
//
// This endpoint allows you to execute Python code and get results back.
// You can optionally specify a kernel_name (defaults to 'python3').
// Use session_id to maintain variable state across multiple requests.
// Sessions automatically expire after 30 minutes of inactivity.
func (c *Client) ExecuteCode(
	ctx context.Context,
	request *sandboxsdkgo.JupyterExecuteRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseJupyterExecuteResponse, error) {
	response, err := c.WithRawResponse.ExecuteCode(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about available Jupyter kernels
func (c *Client) GetInfo(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseJupyterInfoResponse, error) {
	response, err := c.WithRawResponse.GetInfo(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List all active Jupyter sessions
func (c *Client) ListSessions(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseActiveSessionsResult, error) {
	response, err := c.WithRawResponse.ListSessions(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cleanup all active sessions
func (c *Client) DeleteSessions(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.Response, error) {
	response, err := c.WithRawResponse.DeleteSessions(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Manually cleanup a specific session
func (c *Client) DeleteSession(
	ctx context.Context,
	sessionId string,
	opts ...option.RequestOption,
) (*sandboxsdkgo.Response, error) {
	response, err := c.WithRawResponse.DeleteSession(
		ctx,
		sessionId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new Jupyter session
func (c *Client) CreateSession(
	ctx context.Context,
	request *sandboxsdkgo.JupyterCreateSessionRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseJupyterCreateSessionResponse, error) {
	response, err := c.WithRawResponse.CreateSession(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
