// Code generated by Fern. DO NOT EDIT.

package skills

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) RegisterSkills(
	ctx context.Context,
	request *sandboxsdkgo.BodyRegisterSkills,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseSkillRegistrationResult, error) {
	response, err := c.WithRawResponse.RegisterSkills(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListMetadata(
	ctx context.Context,
	request *sandboxsdkgo.SkillsListMetadataRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseSkillMetadataCollection, error) {
	response, err := c.WithRawResponse.ListMetadata(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ClearSkills(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseDict, error) {
	response, err := c.WithRawResponse.ClearSkills(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteSkill(
	ctx context.Context,
	name string,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseSkillMetadata, error) {
	response, err := c.WithRawResponse.DeleteSkill(
		ctx,
		name,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetContent(
	ctx context.Context,
	name string,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseSkillContentResult, error) {
	response, err := c.WithRawResponse.GetContent(
		ctx,
		name,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
