// Code generated by Fern. DO NOT EDIT.

package file

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
	io "io"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Read file content
func (c *Client) ReadFile(
	ctx context.Context,
	request *sandboxsdkgo.FileReadRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileReadResult, error) {
	response, err := c.WithRawResponse.ReadFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Write file content (supports both text and binary files)
//
// For binary files, set encoding to 'base64' and provide base64-encoded content.
// For text files, use default 'utf-8' encoding.
func (c *Client) WriteFile(
	ctx context.Context,
	request *sandboxsdkgo.FileWriteRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileWriteResult, error) {
	response, err := c.WithRawResponse.WriteFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Replace string in file
func (c *Client) ReplaceInFile(
	ctx context.Context,
	request *sandboxsdkgo.FileReplaceRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileReplaceResult, error) {
	response, err := c.WithRawResponse.ReplaceInFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Search in file content
func (c *Client) SearchInFile(
	ctx context.Context,
	request *sandboxsdkgo.FileSearchRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileSearchResult, error) {
	response, err := c.WithRawResponse.SearchInFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Find files by name pattern
func (c *Client) FindFiles(
	ctx context.Context,
	request *sandboxsdkgo.FileFindRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileFindResult, error) {
	response, err := c.WithRawResponse.FindFiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Upload file using streaming
func (c *Client) UploadFile(
	ctx context.Context,
	request *sandboxsdkgo.BodyUploadFile,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileUploadResult, error) {
	response, err := c.WithRawResponse.UploadFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Download file using FileResponse
func (c *Client) DownloadFile(
	ctx context.Context,
	request *sandboxsdkgo.FileDownloadFileRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.DownloadFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List path contents with flexible options
func (c *Client) ListPath(
	ctx context.Context,
	request *sandboxsdkgo.FileListRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseFileListResult, error) {
	response, err := c.WithRawResponse.ListPath(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// An filesystem editor tool that allows the agent to
// - view
// - create
// - navigate
// - edit files
// The tool parameters are defined by Anthropic and are not editable.
func (c *Client) StrReplaceEditor(
	ctx context.Context,
	request *sandboxsdkgo.StrReplaceEditorRequest,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseStrReplaceEditorResult, error) {
	response, err := c.WithRawResponse.StrReplaceEditor(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
