// Code generated by Fern. DO NOT EDIT.

package mcp

import (
	context "context"
	sandboxsdkgo "github.com/agent-infra/sandbox-sdk-go"
	core "github.com/agent-infra/sandbox-sdk-go/core"
	internal "github.com/agent-infra/sandbox-sdk-go/internal"
	option "github.com/agent-infra/sandbox-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List all available tools from the specified MCP server
//
// Args:
//
//	server_name: The name of the MCP server as defined in mcp-servers.json
//
// Returns:
//
//	Response containing the list of available tools with their descriptions and parameters
func (c *Client) ListMcpTools(
	ctx context.Context,
	// Name of the MCP server
	serverName string,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseListToolsResultModel, error) {
	response, err := c.WithRawResponse.ListMcpTools(
		ctx,
		serverName,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Execute a specific tool on the specified MCP server
//
// Args:
//
//	server_name: The name of the MCP server as defined in mcp-servers.json
//	tool_name: The name of the tool to execute
//	arguments: Tool arguments dictionary
//
// Returns:
//
//	Response containing the tool execution results
func (c *Client) ExecuteMcpTool(
	ctx context.Context,
	// Name of the MCP server
	serverName string,
	// Name of the tool to execute
	toolName string,
	request map[string]any,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseCallToolResultModel, error) {
	response, err := c.WithRawResponse.ExecuteMcpTool(
		ctx,
		serverName,
		toolName,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List all configured MCP servers
//
// Returns:
//
//	Response containing the list of configured and filtered MCP servers
func (c *Client) ListMcpServers(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sandboxsdkgo.ResponseListStr, error) {
	response, err := c.WithRawResponse.ListMcpServers(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
